# Generated by Django 4.1.13 on 2024-01-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proiect", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="topic",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="workplace",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
