# Generated by Django 4.1.13 on 2024-01-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proiect", "0002_uploadeddocument_topic_uploadeddocument_workplace"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="current_workplace",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="references",
            field=models.TextField(blank=True, null=True),
        ),
    ]
