# Generated by Django 4.1.13 on 2024-01-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proiect", "0003_customuser_current_workplace_customuser_references"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewerRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("current_workplace", models.CharField(max_length=255)),
                ("references", models.TextField(blank=True, null=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
