# Generated by Django 4.1.13 on 2024-05-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0004_reviewerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('SUBMITTED', 'Submitted for Review'), ('UNDER_REVIEW', 'Currently under Review'), ('REVIEWED', 'Reviewed')], default='UPLOADED', max_length=20),
        ),
    ]
