# Generated by Django 4.1.13 on 2024-05-10 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0005_uploadeddocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('SUBMITTED', 'Submitted for Review'), ('UNDER_REVIEW', 'Under Review'), ('REVIEWED', 'Reviewed')], default='UPLOADED', max_length=20),
        ),
    ]
