# Generated by Django 4.1.13 on 2024-05-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0006_uploadeddocument_reviewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_tracker',
            field=models.BooleanField(default=False),
        ),
    ]
