# Generated by Django 4.1.13 on 2024-05-20 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0008_conference_customuser_joined_conferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='conference',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
