# Generated by Django 4.1.13 on 2024-05-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0011_rename_workplace_uploadeddocument_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='proiect.conference'),
        ),
    ]
