# Generated by Django 4.1.13 on 2024-05-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0012_uploadeddocument_conference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('SUBMITTED', 'Submitted for Review'), ('UNDER_REVIEW', 'Under Review'), ('REVIEWED', 'Reviewed'), ('REJECTED', 'Rejected')], default='UPLOADED', max_length=20),
        ),
    ]
